
# Info
title: Nova Therapy
baseurl: ""
url: https://www.novatherapy.com

# Collections

# Gems

# Settings
markdown: kramdown
destination: dist
sass:
  sass_dir: assets/css
  style: compressed
exclude:
- Gemfile
- Gemfile.lock
- ".gitignore"
- node_modules
- webpack.config.js
- package.json
- package-lock.json
- .jshintrc
- .sass-cache
- browsersync.config.js
- npm-debug.log
- README.md
- buildspec.yml