backend:
  name: git-gateway
  branch: master
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
collections:
  - name: "pages"
    label: "Pages"
    create: false
    editor: false
    files:
      - label: "Home Page"
        name: "home"
        file: "content/_index.json"
        fields:
          - label: "Header"
            name: "header"
            widget: "object"
            fields:
              - {label: "Headline", name: "headline", widget: "string"}
              - {label: "Description", name: "description", widget: "string"}
              - {label: "Button Text", name: "buttontext", widget: "string"}
          - label: "Value Props"
            name: "props"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "string"}
          - label: "Content Overview"
            name: "overview"
            widget: "object"
            fields:
              - label: "About Nova Remedy"
                name: "about"
                widget: "object"
                fields:
                  - {label: "Headline", name: "headline", widget: "string"}
                  - {label: "Description", name: "description", widget: "string"}
                  - label: "Link"
                    name: "link"
                    widget: "object"
                    fields:
                      - {label: "Link text", name: "text", widget: "string"}
                      - label: "Link to page"
                        name: "page"
                        widget: "select"
                        options:
                          - {label: "About", value: "about"}
                          - {label: "Contact", value: "contact"}
                          - {label: "Health Assessment", value: "health-assessment"}
                          - {label: "Pricing", value: "pricing"}
              - label: "Chronic Disease List"
                name: "diseases"
                widget: "object"
                fields:
                  - {label: "Headline", name: "headline", widget: "string"}
                  - label: "Diseases"
                    name: "diseases"
                    widget: "list"
                    field: {label: "Disease", name: "disease", widget: "string"}
              - label: "Doctor Overview"
                name: "doctor"
                widget: "object"
                fields:
                  - {label: "Headline", name: "headline", widget: "string"}
                  - {label: "Description", name: "description", widget: "string"}
                  - label: "Doctor Information"
                    name: "information"
                    widget: "object"
                    fields:
                      - {label: "Name", name: "name", widget: "string"}
                      - {label: "Title", name: "title", widget: "string"}
                      - {label: "Credentials", name: "credentials", widget: "string"}
                  - label: "Link"
                    name: "link"
                    widget: "object"
                    fields:
                      - {label: "Link text", name: "text", widget: "string"}
                      - label: "Link to page"
                        name: "page"
                        widget: "select"
                        options:
                          - {label: "About", value: "about"}
                          - {label: "Contact", value: "contact"}
                          - {label: "Health Assessment", value: "health-assessment"}
                          - {label: "Pricing", value: "pricing"}
          - label: "Videos"
            name: "videos"
            widget: "object"
            fields:
              - {label: "Headline", name: "headline", widget: "string"}
              - {label: "Description", name: "description", widget: "string"}
              - label: "Videos"
                name: "videos"
                widget: "list"
                fields:
                  - {label: "Headline", name: "headline", widget: "string"}
                  - {label: "Description", name: "description", widget: "string"}
                  - {label: "Exercise Type", name: "type", widget: "string"}
                  - {label: "Benefits", name: "benefits", widget: "string"}
                  - {label: "Uses", name: "uses", widget: "string"}
                  - {label: "Duration", name: "duration", widget: "string"}
          - label: "Process"
            name: "process"
            widget: "object"
            fields:
              - {label: "Headline", name: "headline", widget: "string"}
              - {label: "Description", name: "description", widget: "string"}
              - label: "Link"
                name: "link"
                widget: "object"
                fields:
                  - {label: "Link text", name: "text", widget: "string"}
                  - label: "Link to page"
                    name: "page"
                    widget: "select"
                    options:
                      - {label: "About", value: "about"}
                      - {label: "Contact", value: "contact"}
                      - {label: "Health Assessment", value: "health-assessment"}
                      - {label: "Pricing", value: "pricing"}
              - label: "Steps"
                name: "steps"
                widget: "list"
                fields:
                  - {label: "Title", name: "title", widget: "string"}
                  - {label: "Description", name: "description", widget: "string"}
          - label: "Call to Action"
            name: "cta"
            widget: "object"
            fields:
              - {label: "Link text", name: "text", widget: "string"}
              - label: "Link to page"
                name: "page"
                widget: "select"
                options:
                  - {label: "About", value: "about"}
                  - {label: "Contact", value: "contact"}
                  - {label: "Health Assessment", value: "health-assessment"}
                  - {label: "Pricing", value: "pricing"}
      - label: "About Page"
        name: "about"
        file: "content/_about.json"
        fields:
          - label: "Header"
            name: "header"
            widget: "object"
            fields:
              - {label: "Headline", name: "headline", widget: "string"}
              - {label: "Description", name: "description", widget: "string"}
          - label: "Value Props"
            name: "props"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "string"}
          - label: "Overview"
            name: "overview"
            widget: "object"
            fields:
              - {label: "Headline", name: "headline", widget: "string"}
              - {label: "Description", name: "description", widget: "string"}
              - label: "Cards"
                name: "cards"
                widget: "list"
                fields:
                  - {label: "Title", name: "title", widget: "string"}
                  - {label: "Snippet", name: "snippet", widget: "string"}
                  - {label: "Full description", name: "description", widget: "string"}
                  - label: "Statistic"
                    name: "statistic"
                    widget: "object"
                    fields:
                      - {label: "Number", name: "number", widget: "string"}
                      - {label: "Description", name: "description", widget: "string"}
          - label: "Process"
            name: "process"
            widget: "object"
            fields:
              - {label: "Headline", name: "headline", widget: "string"}
              - {label: "Description", name: "description", widget: "string"}
              - label: "Steps"
                name: "steps"
                widget: "list"
                fields:
                  - {label: "Title", name: "title", widget: "string"}
                  - {label: "Description", name: "description", widget: "string"}
          - label: "Team"
            name: "team"
            widget: "object"
            fields:
              - {label: "Headline", name: "headline", widget: "string"}
              - {label: "Description", name: "description", widget: "string"}
              - label: "Team Members"
                name: "members"
                widget: "list"
                fields:
                  - {label: "Name", name: "name", widget: "string"}
                  - {label: "Title", name: "title", widget: "string"}
                  - {label: "Description", name: "description", widget: "string"}
          - label: "Call to Action"
            name: "cta"
            widget: "object"
            fields:
              - {label: "Link text", name: "text", widget: "string"}
              - label: "Link to page"
                name: "page"
                widget: "select"
                options:
                  - {label: "Contact", value: "contact"}
                  - {label: "Health Assessment", value: "health-assessment"}
                  - {label: "Pricing", value: "pricing"}
      - label: "Pricing Page"
        name: "pricing"
        file: "content/_pricing.json"
        fields:
          - label: "Header"
            name: "header"
            widget: "object"
            fields:
              - {label: "Headline", name: "headline", widget: "string"}
              - {label: "Description", name: "description", widget: "string"}
          - label: "Packages"
            name: "packages"
            widget: "list"
            fields:
              - {label: "Package Name", name: "name", widget: "string"}
              - {label: "Description", name: "description", widget: "string"}
              - {label: "Cost per month", name: "month", widget: "string"}
              - {label: "Cost per year", name: "year", widget: "string"}
              - label: "Features"
                name: "features"
                widget: "list"
                field: {label: "Feature", name: "feature", widget: "string"}
      - label: "Contact Page"
        name: "contact"
        file: "content/_contact.json"
        fields:
          - label: "Header"
            name: "header"
            widget: "object"
            fields:
              - {label: "Headline", name: "headline", widget: "string"}
              - {label: "Description", name: "description", widget: "string"}
          - label: "Contact Methods"
            name: "methods"
            widget: "object"
            fields:
              - label: "Phone Numbers"
                name: "phones"
                widget: "list"
                fields:
                  - {label: "Title", name: "title", widget: "string"}
                  - {label: "Phone Number", name: "number", widget: "string"}
              - label: "Email Addresses"
                name: "emails"
                widget: "list"
                fields:
                  - {label: "Title", name: "title", widget: "string"}
                  - {label: "Email Address", name: "email", widget: "string"}
              - label: "Address"  
                name: "address"
                widget: "object"
                fields:
                  - {label: "Street Address", name: "street", widget: "string"}
                  - {label: "City", name: "city", widget: "string"}
                  - {label: "State", name: "state", widget: "string"}
                  - {label: "Zip Code", name: "zip", widget: "string"}
          - label: "Form"
            name: "form"
            widget: "object"
            fields:
              - {label: "Headline", name: "headline", widget: "string"}
